import Navbar from "./_components/Navbar";
import "./globals.css";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="flex bg-custom-cream">
        <Navbar />
        <main className="flex-grow">{children}</main>
      </body>
    </html>
  );
}
